name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feat/publish

jobs:
  cicd:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Build Link Index
      #   uses: jackyzha0/hugo-obsidian@v2.2
      #   with:
      #     index: true
      #     input: content
      #     output: assets/indices
      #     root: .
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx quartz build --verbose --bundleInfo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: mdg.haeramk.im
